/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param deviceToken
 * @param deviceTokenType
 * @param deviceTokenBundle
 * @param payloadVersion
 */


data class ApiAddDeviceTokenRequest(

    @SerializedName("deviceToken")
    val deviceToken: kotlin.String? = null,

    @SerializedName("deviceTokenType")
    val deviceTokenType: kotlin.String? = null,

    @SerializedName("deviceTokenBundle")
    val deviceTokenBundle: kotlin.String? = null,

    @SerializedName("payloadVersion")
    val payloadVersion: kotlin.Long? = null

)

