/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param gender 
 * @param password 
 * @param email 
 * @param company 
 * @param phone 
 */


data class ApiChangeContractDataRequest (

    @SerializedName("firstName")
    val firstName: kotlin.String? = null,

    @SerializedName("lastName")
    val lastName: kotlin.String? = null,

    @SerializedName("gender")
    val gender: kotlin.String? = null,

    @SerializedName("password")
    val password: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("company")
    val company: kotlin.String? = null,

    @SerializedName("phone")
    val phone: kotlin.String? = null

)

