/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param firstName
 * @param lastName
 * @param email
 * @param registrationDate a timestamp as an ISO 8601 date time with an offset
 * @param contractId
 * @param gender
 * @param phone
 * @param company
 * @param consents
 * @param fields 
 */


data class ApiContract (

    @SerializedName("firstName")
    val firstName: kotlin.String? = null,

    @SerializedName("lastName")
    val lastName: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("registrationDate")
    val registrationDate: java.time.OffsetDateTime? = null,

    @SerializedName("contractId")
    val contractId: kotlin.String? = null,

    @SerializedName("gender")
    val gender: kotlin.String? = null,

    @SerializedName("phone")
    val phone: kotlin.String? = null,

    @SerializedName("company")
    val company: kotlin.String? = null,

    @SerializedName("consents")
    val consents: kotlin.collections.List<ApiUserConsent>? = null,

    @SerializedName("fields")
    val fields: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

