/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param targetType 
 * @param comment 
 */


data class ApiConvertTimelineTypeRestRequestData (

    @SerializedName("targetType")
    val targetType: kotlin.String? = null,

    @SerializedName("comment")
    val comment: kotlin.String? = null

)

