/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param messages
 * @param deletedIds
 */


data class ApiGetMessagesResponseData(

    @SerializedName("messages")
    val messages: kotlin.collections.List<ApiMessage>? = null,

    @SerializedName("deletedIds")
    val deletedIds: kotlin.collections.List<kotlin.Long>? = null

)

