/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param timelineItemBaseList 
 */


data class ApiMoveTimelineResponseData (

    @SerializedName("timelineItemBaseList")
    val timelineItemBaseList: kotlin.collections.List<ApiMoveTimelineItemBase>? = null

)

