/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param type
 * @param startIsoTime a timestamp as an ISO 8601 date time with an offset
 * @param endIsoTime a timestamp as an ISO 8601 date time with an offset
 * @param durationMinutes
 */


data class ApiMoveDistractionEvent(

    @SerializedName("type")
    val type: ApiDistractionEventType? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("startIsoTime")
    val startIsoTime: java.time.OffsetDateTime? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("endIsoTime")
    val endIsoTime: java.time.OffsetDateTime? = null,

    @SerializedName("durationMinutes")
    val durationMinutes: kotlin.Long? = null

)

