/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param text
 * @param url
 * @param preview
 * @param action
 * @param deleted
 * @param read
 * @param topic
 * @param sentTime a timestamp as an ISO 8601 date time with an offset
 * @param vote
 * @param iconType
 */


data class ApiMessage(

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("preview")
    val preview: kotlin.String? = null,

    @SerializedName("action")
    val action: kotlin.String? = null,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean? = null,

    @SerializedName("read")
    val read: kotlin.Boolean? = null,

    @SerializedName("topic")
    val topic: kotlin.String? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("sentTime")
    val sentTime: java.time.OffsetDateTime? = null,

    @SerializedName("vote")
    val vote: kotlin.String? = null,

    @SerializedName("iconType")
    val iconType: kotlin.String? = null

)

