/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param period
 * @param startDate an ISO 8601 date
 * @param safeness
 * @param distraction
 * @param speed
 * @param total
 */


data class ApiMoveScoringHistoryResponseData(

    @SerializedName("period")
    val period: ApiPeriodType? = null,

    /* an ISO 8601 date */
    @SerializedName("startDate")
    val startDate: java.time.LocalDate? = null,

    @SerializedName("safeness")
    val safeness: kotlin.collections.List<ApiMoveScoringHistoryItem>? = null,

    @SerializedName("distraction")
    val distraction: kotlin.collections.List<ApiMoveScoringHistoryItem>? = null,

    @SerializedName("speed")
    val speed: kotlin.collections.List<ApiMoveScoringHistoryItem>? = null,

    @SerializedName("total")
    val total: kotlin.collections.List<ApiMoveScoringHistoryItem>? = null

)

