/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param startLat 
 * @param startLon 
 * @param endLat 
 * @param endLon 
 * @param previousTripId 
 * @param nextTripId 
 * @param tripPoints 
 * @param distractionDetails 
 * @param distractionEvents 
 * @param sectionDistance 
 * @param drivingEvents 
 */


data class ApiMoveTimelineItemDetailAllOf (

    @SerializedName("startLat")
    val startLat: kotlin.Double? = null,

    @SerializedName("startLon")
    val startLon: kotlin.Double? = null,

    @SerializedName("endLat")
    val endLat: kotlin.Double? = null,

    @SerializedName("endLon")
    val endLon: kotlin.Double? = null,

    @SerializedName("previousTripId")
    val previousTripId: kotlin.Long? = null,

    @SerializedName("nextTripId")
    val nextTripId: kotlin.Long? = null,

    @SerializedName("tripPoints")
    val tripPoints: kotlin.collections.List<ApiMoveTripPoint>? = null,

    @SerializedName("distractionDetails")
    val distractionDetails: ApiMoveDistractionDetails? = null,

    @SerializedName("distractionEvents")
    val distractionEvents: kotlin.collections.List<ApiMoveDistractionEvent>? = null,

    @SerializedName("sectionDistance")
    val sectionDistance: ApiMoveTripSectionDistance? = null,

    @SerializedName("drivingEvents")
    val drivingEvents: kotlin.collections.List<ApiMoveDrivingEvent>? = null

)

