/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param type
 * @param startAddress
 * @param startTs a timestamp as an ISO 8601 date time with an offset
 * @param endAddress
 * @param endTs a timestamp as an ISO 8601 date time with an offset
 * @param scores
 * @param distanceMeters
 * @param averageSpeedKmh
 * @param durationMinutes
 * @param startLat
 * @param startLon
 * @param endLat
 * @param endLon
 * @param previousTripId
 * @param nextTripId
 * @param tripPoints
 * @param distractionDetails
 * @param distractionEvents
 * @param sectionDistance
 * @param drivingEvents 
 */


data class ApiMoveTimelineItemDetail (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("type")
    val type: ApiTimelineItemType? = null,

    @SerializedName("startAddress")
    val startAddress: kotlin.String? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("startTs")
    val startTs: java.time.OffsetDateTime? = null,

    @SerializedName("endAddress")
    val endAddress: kotlin.String? = null,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("endTs")
    val endTs: java.time.OffsetDateTime? = null,

    @SerializedName("scores")
    val scores: ApiMoveScores? = null,

    @SerializedName("distanceMeters")
    val distanceMeters: kotlin.Long? = null,

    @SerializedName("averageSpeedKmh")
    val averageSpeedKmh: kotlin.Long? = null,

    @SerializedName("durationMinutes")
    val durationMinutes: kotlin.Long? = null,

    @SerializedName("startLat")
    val startLat: kotlin.Double? = null,

    @SerializedName("startLon")
    val startLon: kotlin.Double? = null,

    @SerializedName("endLat")
    val endLat: kotlin.Double? = null,

    @SerializedName("endLon")
    val endLon: kotlin.Double? = null,

    @SerializedName("previousTripId")
    val previousTripId: kotlin.Long? = null,

    @SerializedName("nextTripId")
    val nextTripId: kotlin.Long? = null,

    @SerializedName("tripPoints")
    val tripPoints: kotlin.collections.List<ApiMoveTripPoint>? = null,

    @SerializedName("distractionDetails")
    val distractionDetails: ApiMoveDistractionDetails? = null,

    @SerializedName("distractionEvents")
    val distractionEvents: kotlin.collections.List<ApiMoveDistractionEvent>? = null,

    @SerializedName("sectionDistance")
    val sectionDistance: ApiMoveTripSectionDistance? = null,

    @SerializedName("drivingEvents")
    val drivingEvents: kotlin.collections.List<ApiMoveDrivingEvent>? = null

)

