/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param safeness 
 * @param distraction 
 * @param speed 
 * @param total 
 */


data class ApiMoveScores (

    @SerializedName("safeness")
    val safeness: kotlin.Long? = null,

    @SerializedName("distraction")
    val distraction: kotlin.Long? = null,

    @SerializedName("speed")
    val speed: kotlin.Long? = null,

    @SerializedName("total")
    val total: kotlin.Long? = null

)

