/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param green 
 * @param yellow 
 * @param red 
 */


data class ApiMoveTripSectionDistance (

    @SerializedName("green")
    val green: kotlin.Long? = null,

    @SerializedName("yellow")
    val yellow: kotlin.Long? = null,

    @SerializedName("red")
    val red: kotlin.Long? = null

)

