/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param `value`
 * @param time a timestamp as an ISO 8601 date time with an offset
 * @param lat
 * @param lon
 * @param type
 */


data class ApiMoveDrivingEvent(

    @SerializedName("value")
    val `value`: kotlin.Int,

    /* a timestamp as an ISO 8601 date time with an offset */
    @SerializedName("time")
    val time: java.time.OffsetDateTime? = null,

    @SerializedName("lat")
    val lat: kotlin.Double? = null,

    @SerializedName("lon")
    val lon: kotlin.Double? = null,

    @SerializedName("type")
    val type: ApiDBEType? = null

)

