/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param distractedSwipeTypeMinutes 
 * @param distractedPhoneHandheldMinutes 
 * @param distractionFreeMinutes 
 * @param totalDistractedMinutes 
 * @param distractedSwipeTypePct 
 * @param distractedPhoneHandheldPct 
 * @param distractionFreePct 
 */


data class ApiMoveDistractionDetails (

    @SerializedName("distractedSwipeTypeMinutes")
    val distractedSwipeTypeMinutes: kotlin.Long? = null,

    @SerializedName("distractedPhoneHandheldMinutes")
    val distractedPhoneHandheldMinutes: kotlin.Long? = null,

    @SerializedName("distractionFreeMinutes")
    val distractionFreeMinutes: kotlin.Long? = null,

    @SerializedName("totalDistractedMinutes")
    val totalDistractedMinutes: kotlin.Long? = null,

    @SerializedName("distractedSwipeTypePct")
    val distractedSwipeTypePct: kotlin.Int? = null,

    @SerializedName("distractedPhoneHandheldPct")
    val distractedPhoneHandheldPct: kotlin.Int? = null,

    @SerializedName("distractionFreePct")
    val distractionFreePct: kotlin.Int? = null

)

