/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code Error code, 0 = OK, negative means some error
 * @param message error message or the string 'OK'
 * @param textCode Text error code (optional)
 * @param technicalMsg 
 */


data class ApiStatus (

    /* Error code, 0 = OK, negative means some error */
    @SerializedName("code")
    val code: kotlin.Long,

    /* error message or the string 'OK' */
    @SerializedName("message")
    val message: kotlin.String,

    /* Text error code (optional) */
    @SerializedName("textCode")
    val textCode: kotlin.String? = null,

    @SerializedName("technicalMsg")
    val technicalMsg: kotlin.String? = null

)

