/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.dolphin.move.android.basedata.network.responses


import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param reason
 */


data class ApiTripRemovalReason(

    @SerializedName("id")
    val id: kotlin.Long,

    @SerializedName("reason")
    val reason: kotlin.String? = null

)

